/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Guis;

import dbServices.DBServiceInvoker;
import dbServices.DBServiceInvokerSemicolon;
import java.awt.Frame;
import java.util.regex.Pattern;
import utils.*;
import javax.swing.ComboBoxModel;

/**
 *
 * @author Juraj
 */
public class AddCurrentProduct extends javax.swing.JFrame {
    String id;
    String idRecord;
    
    /**
     * Creates new form <code>AddCurrentProduct</code>
     */
    public AddCurrentProduct() {
        initComponents();
        this.id=null;
        this.idRecord=null;
        setProductId();
        setSupplierId();
    }
    
    /** Creates new form <code>AddCurrentProduct</code>  
     * with selected loaded values
     * 
     */
    public AddCurrentProduct(String id) {
        this();
        this.id=id;
        if(!id.equals("")){
        
            System.out.println(id);
            String[] substring = id.split(Pattern.quote(";"));
            System.out.println(substring.length);
            this.idRecord = substring[0];
            idCurrentProductTextField.setText(substring[0]);
            idProductTextField.setText(substring[1]);
            idSupplierTextField.setText(substring[2]);
            supplierPriceTextField.setText(substring[3]);
            listPriceTextField.setText(substring[4]);
            
            System.out.println(idRecord);
        }
    }
    /** registers ID value from <code>class Product</code>} into text field
     * 
     */
    public void setProductId(){
        idProductTextField.setText(Product.getID());
    }
    
    /** registers ID value from <code>class Supplier</code>} into text field
     * 
     */
    public void setSupplierId(){
        idSupplierTextField.setText(Supplier.getID());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idCurrentProductTextField = new javax.swing.JTextField();
        supplierPriceTextField = new javax.swing.JTextField();
        idProductTextField = new javax.swing.JTextField();
        idSupplierTextField = new javax.swing.JTextField();
        idCurrentProductLabel = new javax.swing.JLabel();
        listPriceLabel = new javax.swing.JLabel();
        idProductLabel = new javax.swing.JLabel();
        supplierIdLabel = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        supplierPriceLabel = new javax.swing.JLabel();
        listPriceTextField = new javax.swing.JTextField();
        selectProductIDButton = new javax.swing.JButton();
        selectSupplierButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add/Edit Current Product");

        idCurrentProductTextField.setEditable(false);
        idCurrentProductTextField.setText("will be filled automatically");

        idProductTextField.setEditable(false);
        idProductTextField.setText("to be filled automatically");
        idProductTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProductTextFieldActionPerformed(evt);
            }
        });

        idSupplierTextField.setEditable(false);
        idSupplierTextField.setText("to be filled automatically");

        idCurrentProductLabel.setText("Current product ID:");

        listPriceLabel.setText("Our Listing Price:");

        idProductLabel.setText("Product:");

        supplierIdLabel.setText("Supplier:");

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        supplierPriceLabel.setText("Supplier's Price:");

        listPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPriceTextFieldActionPerformed(evt);
            }
        });

        selectProductIDButton.setText("Choose..");
        selectProductIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectProductIDButtonActionPerformed(evt);
            }
        });

        selectSupplierButton.setText("Choose..");
        selectSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSupplierButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idCurrentProductLabel)
                            .addComponent(idProductLabel)
                            .addComponent(supplierIdLabel)
                            .addComponent(listPriceLabel)
                            .addComponent(supplierPriceLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplierPriceTextField)
                            .addComponent(listPriceTextField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(idCurrentProductTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(idSupplierTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idProductTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectProductIDButton)
                                    .addComponent(selectSupplierButton))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCurrentProductTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idCurrentProductLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idProductTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idProductLabel)
                    .addComponent(selectProductIDButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idSupplierTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierIdLabel)
                    .addComponent(selectSupplierButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierPriceLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listPriceLabel)
                    .addComponent(listPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /** does SQL INSERT when no record was selected prior to save - Add new..
     * and it does UPDATE when a record was selected prior to save - Edit
     * Add new or Edit paths get called from <code>class CurrentProducts</code>
     * 
     * @param evt 
     */
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if (id==null){
            DBServiceInvoker invoke = new DBServiceInvoker();
            StringBuilder stringBuild = new StringBuilder();
            stringBuild.append("'");
            stringBuild.append(idProductTextField.getText());
            stringBuild.append("'");
            stringBuild.append(",");
            stringBuild.append("'");
            stringBuild.append(idSupplierTextField.getText());
            stringBuild.append("'");
            stringBuild.append(",");
            stringBuild.append("'");
            stringBuild.append(supplierPriceTextField.getText());
            stringBuild.append("'");
            stringBuild.append(",");
            stringBuild.append("'");
            stringBuild.append(listPriceTextField.getText());
            stringBuild.append("'");
            String attribut = "Product_idProduct, Supplier_idSupplier, SupplierPrice, ListPrice";
            invoke.invokeInsert("current_products",attribut,stringBuild.toString());
        }
        else {
            DBServiceInvokerSemicolon invoke = new DBServiceInvokerSemicolon();
            StringBuilder stringBuild = new StringBuilder();
            stringBuild.append("Product_idProduct = ");
            stringBuild.append("'");
            stringBuild.append(idProductTextField.getText());
            stringBuild.append("'");
            stringBuild.append(",");
            stringBuild.append(" Supplier_idSupplier = ");
            stringBuild.append("'");
            stringBuild.append(idSupplierTextField.getText());
            stringBuild.append("'");
            stringBuild.append(",");
            stringBuild.append(" SupplierPrice = ");
            stringBuild.append("'");
            stringBuild.append(supplierPriceTextField.getText());
            stringBuild.append("'");
            stringBuild.append(",");
            stringBuild.append(" ListPrice = ");
            stringBuild.append("'");
            stringBuild.append(listPriceTextField.getText());
            stringBuild.append("'");
            String attribut = "idCurrentProducts = "+idRecord;
            invoke.invokeUpdate("current_products",attribut,stringBuild.toString());
        }
        CurrentProducts newCurrentProducts = new CurrentProducts();
        newCurrentProducts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.setVisible(false);
        CurrentProducts newCurrentProducts = new CurrentProducts();
        newCurrentProducts.setVisible(true);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void listPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPriceTextFieldActionPerformed

    private void selectProductIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectProductIDButtonActionPerformed
       Product product = new Product();
       product.setVisible(true);
       super.dispose();
    }//GEN-LAST:event_selectProductIDButtonActionPerformed

    private void idProductTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProductTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProductTextFieldActionPerformed

    private void selectSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSupplierButtonActionPerformed
        Supplier supplier = new Supplier();
        supplier.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_selectSupplierButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCurrentProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCurrentProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCurrentProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCurrentProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddCurrentProduct dialog = new AddCurrentProduct();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idCurrentProductLabel;
    private javax.swing.JTextField idCurrentProductTextField;
    private javax.swing.JLabel idProductLabel;
    private javax.swing.JTextField idProductTextField;
    private javax.swing.JTextField idSupplierTextField;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel listPriceLabel;
    private javax.swing.JTextField listPriceTextField;
    private javax.swing.JButton selectProductIDButton;
    private javax.swing.JButton selectSupplierButton;
    private javax.swing.JLabel supplierIdLabel;
    private javax.swing.JLabel supplierPriceLabel;
    private javax.swing.JTextField supplierPriceTextField;
    // End of variables declaration//GEN-END:variables
}
