/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Guis;

import dbServices.DBServiceInvoker;
import dbServices.DBServiceInvokerSemicolon;
import java.util.regex.Pattern;

/**
 *
 * @author Juraj
 */
public class AddOffer extends javax.swing.JFrame {
    private String id;
    private String idRecord;
    private String supplierPrice;
    private String listPrice;
    
    /**
     * Creates new form <code>AddCurrentProduct</code>
     */
    public AddOffer() {
        initComponents();
        this.id=null;
        this.idRecord=null;
        setProductId();
        setSupplierId();
        offerDateTextField.setText(CurrentProducts.getSupplierPrice());
        expiryDateTextField.setText(CurrentProducts.getListPrice());
    }
    
    /** Creates new form <code>AddCurrentProduct</code>  
     * with selected loaded values
     * 
     */
    public AddOffer(String id) {
        this();
        this.id=id;
        if(!id.equals("")){
        
            System.out.println(id);
            String[] substring = id.split(Pattern.quote(";"));
            System.out.println(substring.length);
            this.idRecord = substring[0];
            offersIDTextField.setText(substring[0]);
            perkuIDTextField.setText(substring[1]);
            fikuIDTextField.setText(substring[2]);
            offerDateTextField.setText(substring[3]);
            CurrentProducts.setSupplierPrice(offerDateTextField.getText());
            expiryDateTextField.setText(substring[4]);
            CurrentProducts.setListPrice(expiryDateTextField.getText());
            
            
            System.out.println(idRecord);
        }
    }
    /** registers ID value from <code>class Product</code>} into text field
     * 
     */
    public void setProductId(){
        perkuIDTextField.setText(Product.getID());
    }
    
    /** registers ID value from <code>class Supplier</code>} into text field
     * 
     */
    public void setSupplierId(){
        fikuIDTextField.setText(Supplier.getID());
    }
    /** sets variable <code>supplierPrice</code> to value of corresponding 
     * TextField
     */
    public void setSupplierPrice(String s){
        supplierPrice=s;
    }
    /** sets variable <code>listPrice</code> to value of corresponding 
     * TextField
     */
    public void setListPrice(String s){
        listPrice=s;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        offersIDTextField = new javax.swing.JTextField();
        offerDateTextField = new javax.swing.JTextField();
        perkuIDTextField = new javax.swing.JTextField();
        fikuIDTextField = new javax.swing.JTextField();
        offerIDLabel = new javax.swing.JLabel();
        expiryDateLabel = new javax.swing.JLabel();
        customerIDLabel = new javax.swing.JLabel();
        supplierIdLabel = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        offerDateLabel = new javax.swing.JLabel();
        expiryDateTextField = new javax.swing.JTextField();
        selectPerkuButton = new javax.swing.JButton();
        selectFikuButton = new javax.swing.JButton();
        previousOfferIDLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add/Edit Offer");

        offersIDTextField.setEditable(false);
        offersIDTextField.setText("fills out automatically");

        perkuIDTextField.setEditable(false);
        perkuIDTextField.setText("to be filled automatically");
        perkuIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perkuIDTextFieldActionPerformed(evt);
            }
        });

        fikuIDTextField.setEditable(false);
        fikuIDTextField.setText("to be filled automatically");

        offerIDLabel.setText("Offer ID:");

        expiryDateLabel.setText("Expiry Date:");

        customerIDLabel.setText("Customer ID:");

        supplierIdLabel.setText("Company ID:");

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        offerDateLabel.setText("Offer Date:");

        expiryDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryDateTextFieldActionPerformed(evt);
            }
        });

        selectPerkuButton.setText("Choose..");
        selectPerkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPerkuButtonActionPerformed(evt);
            }
        });

        selectFikuButton.setText("Choose..");
        selectFikuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFikuButtonActionPerformed(evt);
            }
        });

        previousOfferIDLabel.setText("Previous Offer:");

        jButton1.setText("Choose..");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSave)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(offerIDLabel)
                            .addComponent(customerIDLabel)
                            .addComponent(supplierIdLabel)
                            .addComponent(expiryDateLabel)
                            .addComponent(offerDateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(offerDateTextField)
                            .addComponent(expiryDateTextField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(offersIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fikuIDTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(perkuIDTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectPerkuButton)
                                    .addComponent(selectFikuButton)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previousOfferIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(offersIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(offerIDLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perkuIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIDLabel)
                    .addComponent(selectPerkuButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fikuIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierIdLabel)
                    .addComponent(selectFikuButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(offerDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(offerDateLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expiryDateLabel)
                    .addComponent(expiryDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousOfferIDLabel)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /** does SQL INSERT when no record was selected prior to save - Add new..
     * and it does UPDATE when a record was selected prior to save - Edit
     * Add new or Edit paths get called from <code>class CurrentProducts</code>
     * 
     * @param evt 
     */
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if (id==null){
            DBServiceInvoker invoke = new DBServiceInvoker();
            StringBuilder stringBuild = new StringBuilder();
            stringBuild.append("'");
            stringBuild.append(perkuIDTextField.getText());
            stringBuild.append("'");
            stringBuild.append(",");
            stringBuild.append("'");
            stringBuild.append(fikuIDTextField.getText());
            stringBuild.append("'");
            stringBuild.append(",");
            stringBuild.append("'");
            stringBuild.append(offerDateTextField.getText());
            stringBuild.append("'");
            stringBuild.append(",");
            stringBuild.append("'");
            stringBuild.append(expiryDateTextField.getText());
            stringBuild.append("'");
            String attribut = "Product_idProduct, Supplier_idSupplier, SupplierPrice, ListPrice";
            invoke.invokeInsert("current_products",attribut,stringBuild.toString());
        }
        else {
            DBServiceInvokerSemicolon invoke = new DBServiceInvokerSemicolon();
            StringBuilder stringBuild = new StringBuilder();
            stringBuild.append("Product_idProduct = ");
            stringBuild.append("'");
            stringBuild.append(perkuIDTextField.getText());
            stringBuild.append("'");
            stringBuild.append(",");
            stringBuild.append(" Supplier_idSupplier = ");
            stringBuild.append("'");
            stringBuild.append(fikuIDTextField.getText());
            stringBuild.append("'");
            stringBuild.append(",");
            stringBuild.append(" SupplierPrice = ");
            stringBuild.append("'");
            stringBuild.append(offerDateTextField.getText());
            stringBuild.append("'");
            stringBuild.append(",");
            stringBuild.append(" ListPrice = ");
            stringBuild.append("'");
            stringBuild.append(expiryDateTextField.getText());
            stringBuild.append("'");
            String attribut = "idCurrentProducts = "+idRecord;
            invoke.invokeUpdate("current_products",attribut,stringBuild.toString());
        }
        CurrentProducts newCurrentProducts = new CurrentProducts();
        newCurrentProducts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.setVisible(false);
        CurrentProducts newCurrentProducts = new CurrentProducts();
        newCurrentProducts.setVisible(true);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void expiryDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDateTextFieldActionPerformed

    private void selectPerkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPerkuButtonActionPerformed
       Product product = new Product();
       product.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_selectPerkuButtonActionPerformed

    private void perkuIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perkuIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perkuIDTextFieldActionPerformed

    private void selectFikuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFikuButtonActionPerformed
        Supplier supplier = new Supplier();
        supplier.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_selectFikuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddOffer dialog = new AddOffer();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerIDLabel;
    private javax.swing.JLabel expiryDateLabel;
    private javax.swing.JTextField expiryDateTextField;
    private javax.swing.JTextField fikuIDTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel offerDateLabel;
    private javax.swing.JTextField offerDateTextField;
    private javax.swing.JLabel offerIDLabel;
    private javax.swing.JTextField offersIDTextField;
    private javax.swing.JTextField perkuIDTextField;
    private javax.swing.JLabel previousOfferIDLabel;
    private javax.swing.JButton selectFikuButton;
    private javax.swing.JButton selectPerkuButton;
    private javax.swing.JLabel supplierIdLabel;
    // End of variables declaration//GEN-END:variables
}
