/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Guis;

import dbServices.DBServiceInvoker;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;

/**
 *
 * @author Kain
 */
public class Perku extends javax.swing.JFrame {
    public DefaultListModel getModels(String table, String where){
    DBServiceInvoker invoke = new DBServiceInvoker();
    DefaultListModel model = new DefaultListModel();
        try {
            java.util.List<String> list = invoke.invokeSelect(table, where);
            
            Iterator<String> i = list.iterator();
            while(i.hasNext()){
                StringBuilder stringBuilder = new StringBuilder();
                String[] substring = i.next().split(Pattern.quote(" "));
                for(int j=0;j<3;j++){
                    stringBuilder.append(substring[j]);
                    stringBuilder.append(" ");
                }
                model.addElement(stringBuilder.toString());
               
            }
            }catch(SQLException sqlex){System.out.println(sqlex);}
    return model;
}

    /**
     * Creates new form Perku
     */
    public Perku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        perkuList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        perkuTextArea = new javax.swing.JTextArea();
        personenKundenLabel = new javax.swing.JLabel();
        listeDerPerKuLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        newPerkuButton = new javax.swing.JButton();
        editPerkuButton = new javax.swing.JButton();
        infoPerkuButton = new javax.swing.JButton();
        showPerkuButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(perkuList);

        perkuTextArea.setEditable(false);
        perkuTextArea.setColumns(20);
        perkuTextArea.setRows(5);
        jScrollPane2.setViewportView(perkuTextArea);

        personenKundenLabel.setText("Customer");

        listeDerPerKuLabel.setText("List of Customers");

        infoLabel.setText("Infos");

        newPerkuButton.setText("New");
        newPerkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPerkuButtonActionPerformed(evt);
            }
        });

        editPerkuButton.setText("Edit");
        editPerkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPerkuButtonActionPerformed(evt);
            }
        });

        infoPerkuButton.setText("Info");
        infoPerkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoPerkuButtonActionPerformed(evt);
            }
        });

        showPerkuButton.setText("Show");
        showPerkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPerkuButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(listeDerPerKuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoLabel)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(personenKundenLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(newPerkuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(editPerkuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infoPerkuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(showPerkuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(personenKundenLabel)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listeDerPerKuLabel)
                    .addComponent(infoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPerkuButton)
                    .addComponent(editPerkuButton)
                    .addComponent(infoPerkuButton)
                    .addComponent(showPerkuButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPerkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPerkuButtonActionPerformed
        // TODO add your handling code here:
        AddPerku newPerku = new AddPerku(null,true);
        newPerku.setVisible(true);
    }//GEN-LAST:event_newPerkuButtonActionPerformed

    private void editPerkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPerkuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPerkuButtonActionPerformed

    private void infoPerkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoPerkuButtonActionPerformed
        // TODO add your handling code here:
        DBServiceInvoker invoke = new DBServiceInvoker();
        try {
            perkuTextArea.setText("");
            for(String info : invoke.invokeSelect("perku", " ")){
                 
                    perkuTextArea.append(info);
                    perkuTextArea.append("\n");
                }
            
         }catch(SQLException sqlex){System.out.println(sqlex);}
    }//GEN-LAST:event_infoPerkuButtonActionPerformed

    private void showPerkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPerkuButtonActionPerformed
        // TODO add your handling code here:
        perkuList.setModel(this.getModels("perku"," "));
    }//GEN-LAST:event_showPerkuButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editPerkuButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton infoPerkuButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel listeDerPerKuLabel;
    private javax.swing.JButton newPerkuButton;
    private javax.swing.JList perkuList;
    private javax.swing.JTextArea perkuTextArea;
    private javax.swing.JLabel personenKundenLabel;
    private javax.swing.JButton showPerkuButton;
    // End of variables declaration//GEN-END:variables
}
